// <auto-generated />
using System;
using Gym_Management__Project_.INFRASTRUCTURE.EFRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gym_Management__Project_.Migrations
{
    [DbContext(typeof(GymDbContext))]
    partial class GymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gym_Management__Project_.DOMAIN.Entities.Members", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CardStatus")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscribtionType")
                        .HasColumnType("int");

                    b.Property<int?>("TrainersId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainersId1");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Gym_Management__Project_.DOMAIN.Entities.Trainers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("Gym_Management__Project_.DOMAIN.Entities.Workouts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MembersId")
                        .HasColumnType("int");

                    b.Property<int?>("MembersId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembersId");

                    b.HasIndex("MembersId1");

                    b.HasIndex("TrainersId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Gym_Management__Project_.DOMAIN.Entities.Members", b =>
                {
                    b.HasOne("Gym_Management__Project_.DOMAIN.Entities.Trainers", "Trainers")
                        .WithMany("Members")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_Management__Project_.DOMAIN.Entities.Trainers", null)
                        .WithMany("members")
                        .HasForeignKey("TrainersId1");
                });

            modelBuilder.Entity("Gym_Management__Project_.DOMAIN.Entities.Workouts", b =>
                {
                    b.HasOne("Gym_Management__Project_.DOMAIN.Entities.Members", null)
                        .WithMany("MemberWorkouts")
                        .HasForeignKey("MembersId");

                    b.HasOne("Gym_Management__Project_.DOMAIN.Entities.Members", null)
                        .WithMany("Workouts")
                        .HasForeignKey("MembersId1");

                    b.HasOne("Gym_Management__Project_.DOMAIN.Entities.Trainers", null)
                        .WithMany("Schedule")
                        .HasForeignKey("TrainersId");

                    b.OwnsMany("Gym_Management__Project_.DOMAIN.Entities.Exercises", "Exercises", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("int");

                            b1.Property<double>("MET")
                                .HasColumnType("float");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)")
                                .HasMaxLength(100);

                            b1.Property<int>("WorkoutPlanId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutPlanId");

                            b1.ToTable("Exercises");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutPlanId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
